// Level-specific common issues/mistakes tags for student profiles

export const COMMON_ISSUES_BY_LEVEL: Record<string, string[]> = {
  'Beginner': [
    'Forgets subject in sentence ("Is cold" instead of "It is cold")',
    'Wrong word order in questions ("You like?" instead of "Do you like?")',
    'Omits articles ("I have car" instead of "I have a car")',
    'Confuses he/she/it pronouns',
    'Forgets -s in third person ("He go" instead of "He goes")',
    'Uses "no" instead of "not" ("I no understand")',
    'Confuses am/is/are',
    'Uses present for everything — no past tense attempt',
    'Translates word-for-word from native language',
    'Wrong preposition with places ("I live at London")',
    'Drops plural -s ("two book")',
    'Confuses this/that/these/those',
    'Says "have 25 years" instead of "am 25 years old"',
    'Struggles to form negative sentences',
    'Pronounces silent letters',
  ],
  'Elementary Low': [
    'Forgets auxiliary in questions ("Where you go?")',
    'Double negatives ("I don\'t have nothing")',
    'Confuses don\'t/doesn\'t',
    'Uses wrong past tense form ("I goed" instead of "I went")',
    'Adds -ed to irregular verbs ("I eated")',
    'Confuses much/many',
    'Says "more big" instead of "bigger"',
    'Wrong use of some/any',
    'Confuses there/their/they\'re',
    'Omits "do" in negative ("I not like" instead of "I don\'t like")',
    'Uses "is" with plural ("The dogs is")',
    'Confuses countable/uncountable ("an advice", "informations")',
    'Wrong preposition of time ("in Monday" instead of "on Monday")',
    'Confuses can/can\'t pronunciation',
    'Uses adjective as adverb ("He runs quick")',
  ],
  'Elementary High': [
    'Confuses Past Simple and Past Continuous',
    'Uses "was" for all past ("I was go")',
    'Forgets -ing in continuous ("I am play")',
    'Says "I\'m agree" instead of "I agree"',
    'Confuses "going to" and "will"',
    'Uses "for" instead of "since" with time points',
    'Wrong adverb placement ("I go always")',
    'Confuses say/tell',
    'Uses "make" instead of "do" (or vice versa)',
    'Drops auxiliary in short answers ("Yes, I like" instead of "Yes, I do")',
    'Confuses too/very ("It\'s too nice" meaning "very nice")',
    'Confuses bored/boring, interested/interesting',
    'Uses "the" with general categories ("I like the music")',
    'Pronounces -ed ending incorrectly',
    'Struggles to sequence a story (then/after that/finally)',
  ],
  'Pre-Intermediate Low': [
    'Confuses Present Perfect and Past Simple ("I have been there yesterday")',
    'Uses "ever" in affirmative ("I ever went")',
    'Wrong participle form ("I have went")',
    'Forgets "have" in Perfect ("I been there")',
    'Confuses if + will ("If I will go" instead of "If I go")',
    'Uses "must" for past obligation instead of "had to"',
    'Confuses should/must strength',
    'Wrong gerund/infinitive ("I enjoy to play")',
    'Omits relative pronoun when needed',
    'Passive voice word order errors',
    'Overuses "very" instead of stronger adjectives',
    'Confuses make/let/allow structures',
    'Misplaces stress on multi-syllable words',
    'Struggles to paraphrase — repeats same words',
    'Writes run-on sentences without punctuation',
  ],
  'Pre-Intermediate High': [
    'Confuses Present Perfect Simple and Continuous',
    'Uses Second Conditional with "will" ("If I had, I will")',
    'Wrong tense in reported speech ("He said he goes")',
    'Uses "used to" for present habits incorrectly',
    'Confuses "say me" instead of "tell me"',
    'Separable phrasal verbs used wrong ("I picked up it")',
    'Confuses purpose structures ("for to learn" instead of "to learn")',
    'Overuses "but" — avoids "however/although"',
    'Hedging too weak or absent in opinions',
    'Wrong collocation ("do a decision" instead of "make a decision")',
    'Eats word endings in connected speech',
    'Misses implied meaning in listening',
    'Uses informal register in formal contexts',
    'Writes without paragraph structure',
    'Overuses "I think" as only opinion marker',
  ],
  'Intermediate Low': [
    'Avoids Third Conditional — uses simpler structures',
    'Confuses Second and Third Conditional',
    'Wrong tense after "wish" ("I wish I can" instead of "I wish I could")',
    'Passive voice tense errors',
    'Reported speech backshift errors',
    'Uses "which" for people instead of "who"',
    'Confuses defining/non-defining clauses (missing commas)',
    'Overuses "get" as general verb',
    'Register mismatch (too informal in writing, too formal in speech)',
    'Weak cause/effect linking ("because" only)',
    'Summarizes by copying original words',
    'Weak forms not used — sounds robotic',
    'Difficulty understanding fast native speech',
    'Writes essays without clear thesis',
    'Avoids complex structures — stays in comfort zone',
  ],
  'Intermediate High': [
    'Future Perfect/Continuous formed incorrectly',
    'Avoids inversion ("Never I have seen")',
    'Cleft sentence errors ("What I want is go")',
    'Wrong modal perfect ("He might went" instead of "He might have gone")',
    'Participle clause dangling modifiers',
    'Weak use of ellipsis in speech',
    'Uses idioms incorrectly or out of context',
    'Formal/informal switching mid-text',
    'Weak cohesion — ideas don\'t flow logically',
    'Opinions lack nuance (too absolute)',
    'Poor debate structure — jumps between points',
    'Sentence rhythm sounds flat — no emphasis variation',
    'Misses lecture structure cues (firstly, in contrast)',
    'Writes topic sentences that don\'t control the paragraph',
    'Avoids concession language (admittedly, granted)',
  ],
  'Upper-Intermediate Low': [
    'Subjunctive errors ("I suggest that he goes" instead of "go")',
    'Complex passive sounds unnatural',
    'Overuses emphatic "do" or never uses it',
    'Noun phrases too simple for level',
    'Linking devices used mechanically',
    'Nominalisation attempts are clumsy',
    'Hedging too much or too little in professional context',
    'Confuses connotation — uses words with wrong tone',
    'Paraphrases lose original meaning',
    'Reads critically but can\'t articulate analysis',
    'Presentation structure is weak (no signposting)',
    'Negotiation language too direct or too vague',
    'Pacing unnatural — too many pauses in complex sentences',
    'Can\'t understand unfamiliar accents',
    'Writing tone inconsistent across a document',
  ],
  'Upper-Intermediate High': [
    'Mixed conditionals used with wrong tense combination',
    'Fronting sounds unnatural or forced',
    'Loses control of discourse in long turns',
    'Misses pragmatic cues (sarcasm, politeness levels)',
    'Academic vocabulary used imprecisely',
    'Collocations almost right but slightly off',
    'Attempts humour/irony but tone lands wrong',
    'Phrasal verbs used in wrong register',
    'Can\'t synthesize multiple sources coherently',
    'Persuasive writing lacks rhetorical variety',
    'Emphasis placement changes meaning unintentionally',
    'Misses implied attitudes in listening',
    'Fluency drops significantly on unfamiliar topics',
    'Self-corrects but disrupts flow',
    'Tone shifts unintentionally in long writing',
  ],
  'Advanced': [
    'Style doesn\'t vary across genres (emails sound like essays)',
    'Subtle grammar hedging feels mechanical',
    'Collocations are correct but not native-like',
    'Vocabulary is accurate but lacks variety/richness',
    'Misses ambiguity — interprets too literally',
    'Discourse analysis stays surface-level',
    'Rhetorical devices feel forced',
    'Can\'t fully code-switch between registers mid-conversation',
    'Misses cultural pragmatic norms',
    'Struggles with overlapping speakers / fast informal speech',
    'Writing is correct but lacks voice/personality',
    'Critical analysis lacks depth — describes instead of evaluates',
    'Complex arguments lose coherence in final points',
    'Connected speech still has non-native rhythm patterns',
    'Can identify errors in others but repeats own fossilized mistakes',
  ],
}

export const COURSE_TYPES = ['Group', 'Individual', 'Small Group', 'Self Study']

// Country flags - common countries with their flag emojis
export const COUNTRY_FLAGS: Record<string, string> = {
  'Argentina': '\uD83C\uDDE6\uD83C\uDDF7',
  'Armenia': '\uD83C\uDDE6\uD83C\uDDF2',
  'Australia': '\uD83C\uDDE6\uD83C\uDDFA',
  'Austria': '\uD83C\uDDE6\uD83C\uDDF9',
  'Azerbaijan': '\uD83C\uDDE6\uD83C\uDDFF',
  'Belarus': '\uD83C\uDDE7\uD83C\uDDFE',
  'Belgium': '\uD83C\uDDE7\uD83C\uDDEA',
  'Brazil': '\uD83C\uDDE7\uD83C\uDDF7',
  'Bulgaria': '\uD83C\uDDE7\uD83C\uDDEC',
  'Canada': '\uD83C\uDDE8\uD83C\uDDE6',
  'Chile': '\uD83C\uDDE8\uD83C\uDDF1',
  'China': '\uD83C\uDDE8\uD83C\uDDF3',
  'Colombia': '\uD83C\uDDE8\uD83C\uDDF4',
  'Croatia': '\uD83C\uDDED\uD83C\uDDF7',
  'Czech Republic': '\uD83C\uDDE8\uD83C\uDDFF',
  'Denmark': '\uD83C\uDDE9\uD83C\uDDF0',
  'Egypt': '\uD83C\uDDEA\uD83C\uDDEC',
  'Estonia': '\uD83C\uDDEA\uD83C\uDDEA',
  'Finland': '\uD83C\uDDEB\uD83C\uDDEE',
  'France': '\uD83C\uDDEB\uD83C\uDDF7',
  'Georgia': '\uD83C\uDDEC\uD83C\uDDEA',
  'Germany': '\uD83C\uDDE9\uD83C\uDDEA',
  'Greece': '\uD83C\uDDEC\uD83C\uDDF7',
  'Hungary': '\uD83C\uDDED\uD83C\uDDFA',
  'India': '\uD83C\uDDEE\uD83C\uDDF3',
  'Indonesia': '\uD83C\uDDEE\uD83C\uDDE9',
  'Iran': '\uD83C\uDDEE\uD83C\uDDF7',
  'Iraq': '\uD83C\uDDEE\uD83C\uDDF6',
  'Ireland': '\uD83C\uDDEE\uD83C\uDDEA',
  'Israel': '\uD83C\uDDEE\uD83C\uDDF1',
  'Italy': '\uD83C\uDDEE\uD83C\uDDF9',
  'Japan': '\uD83C\uDDEF\uD83C\uDDF5',
  'Jordan': '\uD83C\uDDEF\uD83C\uDDF4',
  'Kazakhstan': '\uD83C\uDDF0\uD83C\uDDFF',
  'Kuwait': '\uD83C\uDDF0\uD83C\uDDFC',
  'Latvia': '\uD83C\uDDF1\uD83C\uDDFB',
  'Lebanon': '\uD83C\uDDF1\uD83C\uDDE7',
  'Lithuania': '\uD83C\uDDF1\uD83C\uDDF9',
  'Mexico': '\uD83C\uDDF2\uD83C\uDDFD',
  'Moldova': '\uD83C\uDDF2\uD83C\uDDE9',
  'Morocco': '\uD83C\uDDF2\uD83C\uDDE6',
  'Netherlands': '\uD83C\uDDF3\uD83C\uDDF1',
  'New Zealand': '\uD83C\uDDF3\uD83C\uDDFF',
  'Nigeria': '\uD83C\uDDF3\uD83C\uDDEC',
  'Norway': '\uD83C\uDDF3\uD83C\uDDF4',
  'Pakistan': '\uD83C\uDDF5\uD83C\uDDF0',
  'Peru': '\uD83C\uDDF5\uD83C\uDDEA',
  'Philippines': '\uD83C\uDDF5\uD83C\uDDED',
  'Poland': '\uD83C\uDDF5\uD83C\uDDF1',
  'Portugal': '\uD83C\uDDF5\uD83C\uDDF9',
  'Romania': '\uD83C\uDDF7\uD83C\uDDF4',
  'Russia': '\uD83C\uDDF7\uD83C\uDDFA',
  'Saudi Arabia': '\uD83C\uDDF8\uD83C\uDDE6',
  'Serbia': '\uD83C\uDDF7\uD83C\uDDF8',
  'Slovakia': '\uD83C\uDDF8\uD83C\uDDF0',
  'Slovenia': '\uD83C\uDDF8\uD83C\uDDEE',
  'South Africa': '\uD83C\uDDFF\uD83C\uDDE6',
  'South Korea': '\uD83C\uDDF0\uD83C\uDDF7',
  'Spain': '\uD83C\uDDEA\uD83C\uDDF8',
  'Sweden': '\uD83C\uDDF8\uD83C\uDDEA',
  'Switzerland': '\uD83C\uDDE8\uD83C\uDDED',
  'Thailand': '\uD83C\uDDF9\uD83C\uDDED',
  'Turkey': '\uD83C\uDDF9\uD83C\uDDF7',
  'UAE': '\uD83C\uDDE6\uD83C\uDDEA',
  'UK': '\uD83C\uDDEC\uD83C\uDDE7',
  'Ukraine': '\uD83C\uDDFA\uD83C\uDDE6',
  'USA': '\uD83C\uDDFA\uD83C\uDDF8',
  'Uzbekistan': '\uD83C\uDDFA\uD83C\uDDFF',
  'Vietnam': '\uD83C\uDDFB\uD83C\uDDF3',
}
